"""Report generation: JSON, SARIF, HTML, PDF."""

from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from shingan.core.models import SEVERITY_ORDER, ScanResult, Severity
from shingan.core.version import get_version

_TEMPLATES_DIR = Path(__file__).parent.parent / "web" / "templates"
_jinja_env = Environment(loader=FileSystemLoader(str(_TEMPLATES_DIR)), autoescape=True)

_TOOL_URI = "https://github.com/ykus4/shingan"

# ---------------------------------------------------------------------------
# Localization strings (EN / JA)
# ---------------------------------------------------------------------------

_I18N: dict[str, dict[str, str]] = {
    "en": {
        "title": "shingan — Mobile App Security Report",
        "findings": "Findings",
        "critical": "Critical",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Info",
        "recommendation": "Recommendation",
        "evidence": "Evidence",
        "generated_by": "Generated by shingan",
        "badge_new": "NEW",
        "badge_fixed": "FIXED",
        "masvs": "MASVS",
    },
    "ja": {
        "title": "shingan — モバイルアプリ セキュリティレポート",
        "findings": "検出結果",
        "critical": "緊急",
        "high": "高",
        "medium": "中",
        "low": "低",
        "info": "情報",
        "recommendation": "推奨事項",
        "evidence": "証拠",
        "generated_by": "shingan により生成",
        "badge_new": "新規",
        "badge_fixed": "修正済",
        "masvs": "MASVS",
    },
}

DEFAULT_LANG = "en"

# SARIF severity mapping. SARIF has no "critical" level, so the most severe
# findings map to "error" alongside HIGH and carry a rank for ordering.
_SARIF_LEVEL: dict[Severity, str] = {
    Severity.CRITICAL: "error",
    Severity.HIGH: "error",
    Severity.MEDIUM: "warning",
    Severity.LOW: "note",
    Severity.INFO: "none",
}

#: SARIF `rank` (0.0-100.0) conveys the severity that `level` cannot express.
_SARIF_RANK: dict[Severity, float] = {
    Severity.CRITICAL: 100.0,
    Severity.HIGH: 80.0,
    Severity.MEDIUM: 50.0,
    Severity.LOW: 20.0,
    Severity.INFO: 0.0,
}


def _i18n_for(lang: str) -> dict[str, str]:
    return _I18N.get(lang, _I18N[DEFAULT_LANG])


def to_json(result: ScanResult, indent: int = 2) -> str:
    return json.dumps(result.to_dict(), ensure_ascii=False, indent=indent)


def to_text(result: ScanResult) -> str:
    """Render a plain-text report.

    ``--format text --out FILE`` previously wrote an empty file because the
    renderer had no text branch and returned "".
    """
    summary = result.to_dict()["summary"]
    lines = [
        f"shingan report — {result.artifact_name}",
        f"App:      {result.app_id} {result.app_version} ({result.build})",
        f"Platform: {result.platform}",
        f"Scanned:  {result.scanned_at}",
        f"Version:  shingan {get_version()}",
        "",
        "Summary:",
        *(
            f"  {severity.value:<9} {summary[severity.value]}"
            for severity in SEVERITY_ORDER
        ),
        f"  {'total':<9} {summary['total']}",
        f"  {'suppressed':<9} {summary['suppressed']}",
        "",
        "Findings:",
    ]

    if not result.findings:
        lines.append("  (none)")
    else:
        for f in sorted(result.findings, key=lambda x: x.severity.rank):
            lines.append(f"  [{f.severity.value.upper()}] {f.rule_id} — {f.title}")
            if f.masvs:
                lines.append(f"      MASVS: {f.masvs}")
            if f.evidence:
                first_line = f.evidence.splitlines()[0] if f.evidence.strip() else ""
                if first_line:
                    lines.append(f"      Evidence: {first_line}")
            if f.recommendation:
                lines.append(f"      Fix: {f.recommendation}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def to_sarif(result: ScanResult) -> str:
    rules: dict[str, dict] = {}
    for f in result.findings:
        if f.rule_id in rules:
            continue
        rules[f.rule_id] = {
            "id": f.rule_id,
            "name": f.rule_id.replace("-", "_"),
            "shortDescription": {"text": f.title},
            "fullDescription": {"text": f.description},
            "help": {"text": f.recommendation},
            "defaultConfiguration": {"level": _SARIF_LEVEL[f.severity]},
            "properties": {
                "security-severity": str(_SARIF_RANK[f.severity]),
                **({"masvs": f.masvs} if f.masvs else {}),
            },
        }

    sarif = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "shingan",
                        "version": get_version(),
                        "informationUri": _TOOL_URI,
                        "rules": list(rules.values()),
                    }
                },
                "results": [
                    {
                        "ruleId": f.rule_id,
                        "level": _SARIF_LEVEL[f.severity],
                        "rank": _SARIF_RANK[f.severity],
                        "message": {
                            "text": (
                                f"{f.title}\n\n{f.description}\n\n"
                                f"Evidence:\n{f.evidence}\n\n"
                                f"Recommendation:\n{f.recommendation}"
                            )
                        },
                        "locations": [
                            {
                                "physicalLocation": {
                                    "artifactLocation": {
                                        "uri": result.artifact_name,
                                        "uriBaseId": "%SRCROOT%",
                                    }
                                }
                            }
                        ],
                    }
                    for f in result.findings
                ],
            }
        ],
    }
    return json.dumps(sarif, ensure_ascii=False, indent=2)


def to_pdf(
    result: ScanResult,
    diff_new: set[str] | None = None,
    diff_fixed: set[str] | None = None,
    lang: str = DEFAULT_LANG,
) -> bytes:
    """Render result as a PDF via WeasyPrint.

    Requires: ``pip install weasyprint``
    On macOS: ``brew install cairo pango``
    """
    try:
        from weasyprint import HTML as _HTML
    except ImportError as exc:
        raise RuntimeError(
            "weasyprint is required for PDF export. "
            "Install it with: pip install weasyprint\n"
            "On macOS also run: brew install cairo pango"
        ) from exc

    html_str = to_html(result, diff_new=diff_new, diff_fixed=diff_fixed, lang=lang)
    return _HTML(string=html_str).write_pdf()


def to_html(
    result: ScanResult,
    diff_new: set[str] | None = None,
    diff_fixed: set[str] | None = None,
    lang: str = DEFAULT_LANG,
) -> str:
    summary = result.to_dict()["summary"]
    new_fps = diff_new or set()
    fixed_fps = diff_fixed or set()

    findings = []
    for f in result.findings:
        fp = f.fingerprint()
        findings.append(
            {
                "rule_id": f.rule_id,
                "severity": f.severity.value,
                "title": f.title,
                "description": f.description,
                "evidence": f.evidence,
                "recommendation": f.recommendation,
                "masvs": f.masvs,
                "is_new": fp in new_fps,
                "is_fixed": fp in fixed_fps,
            }
        )

    template = _jinja_env.get_template("report.html")
    return template.render(
        ipa_name=result.artifact_name,
        artifact_name=result.artifact_name,
        app_id=result.app_id,
        app_version=result.app_version,
        build=result.build,
        platform=result.platform,
        scanned_at=result.scanned_at,
        critical=summary[Severity.CRITICAL.value],
        high=summary[Severity.HIGH.value],
        medium=summary[Severity.MEDIUM.value],
        low=summary[Severity.LOW.value],
        info_count=summary[Severity.INFO.value],
        total=summary["total"],
        findings=findings,
        i18n=_i18n_for(lang),
        lang=lang,
        version=get_version(),
    )
